CREATE DATABASE DBTEST_CER
GO
USE DBTEST_CER
GO
CREATE TABLE USERS(
	USERID NVARCHAR(10) PRIMARY KEY,
	PASSWORDS NVARCHAR(50) NOT NULL,
	IDENTITYCARD INT NOT NULL,
	GENDER NVARCHAR(5) NOT NULL,
	DOB DATE NOT NULL,
	PHONE INT NOT NULL,
	EMAIL NVARCHAR(20) NOT NULL,
	USERADD NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE STUDENTS(
	STUDENTID NVARCHAR(10) PRIMARY KEY,
	STUDENTNAME NVARCHAR(50) NOT NULL,
	IDENTITYCARD INT NOT NULL,
	GENDER NVARCHAR(5) NOT NULL,
	DOB DATE NOT NULL,
	PHONE INT NOT NULL,
	EMAIL NVARCHAR(20) NOT NULL,
	STUDENTADD NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE CERTIFICATES(
	CERTIFICATEID NVARCHAR(10) PRIMARY KEY,
	CERTIFICATENAME NVARCHAR(100) NOT NULL,
	CERDESCRIPTION NVARCHAR(100) NOT NULL
)
GO 
CREATE TABLE COURSES(
	COURSEID NVARCHAR(10) PRIMARY KEY,
	COURSENAME NVARCHAR(100) NOT NULL,
	DESCRIPTIONS NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE COURSE_CER(
	COURSEID NVARCHAR(10),
	CERTIFICATEID NVARCHAR(10),
	EXAMDATE DATE NOT NULL,
	CONSTRAINT PK_COURSE_CER  PRIMARY KEY(COURSEID,CERTIFICATEID),
	CONSTRAINT FK_COURSECER_COURSEID FOREIGN KEY(COURSEID) REFERENCES COURSES(COURSEID),
	CONSTRAINT FK_COURSECER_CERTIFICATEID FOREIGN KEY(CERTIFICATEID) REFERENCES CERTIFICATES(CERTIFICATEID)
)
GO
CREATE TABLE SUBJECTS(
	SUBJECTID NVARCHAR(5) PRIMARY KEY,
	SUBJECTNAME NVARCHAR(100) NOT NULL,
	CERTIFICATEID NVARCHAR(10),
	CONSTRAINT FK_SUBJECTS_CERTIFICATEID FOREIGN KEY(CERTIFICATEID) REFERENCES CERTIFICATES(CERTIFICATEID)
)
GO
CREATE TABLE EXAMREGISTRY(
	STUDENTID NVARCHAR(10),
	COURSEID NVARCHAR(10),
	CERTIFICATEID NVARCHAR(10),
	RESULT NVARCHAR(10) NULL,
	CONSTRAINT PK_EXAMREGISTRY  PRIMARY KEY(STUDENTID,COURSEID,CERTIFICATEID),
	CONSTRAINT FK_EXAMREGISTRY_STUDENTID FOREIGN KEY(STUDENTID) REFERENCES STUDENTS(STUDENTID),
	CONSTRAINT FK_EXAMREGISTRY_COURSEID FOREIGN KEY(COURSEID) REFERENCES COURSES(COURSEID),
	CONSTRAINT FK_EXAMREGISTRY_CERTIFICATEID FOREIGN KEY(CERTIFICATEID) REFERENCES CERTIFICATES(CERTIFICATEID)
)
GO
CREATE TABLE EXAMMARK(
	STUDENTID NVARCHAR(10),
	COURSEID NVARCHAR(10),
	CERTIFICATEID NVARCHAR(10),
	SUBJECTID NVARCHAR(5),
	MARK FLOAT NULL,
	CONSTRAINT PK_EXAMMARK  PRIMARY KEY(STUDENTID,COURSEID,CERTIFICATEID,SUBJECTID),
	CONSTRAINT FK_EXAMMARK_STUDENTID FOREIGN KEY(STUDENTID) REFERENCES STUDENTS(STUDENTID),
	CONSTRAINT FK_EXAMMARK_COURSEID FOREIGN KEY(COURSEID) REFERENCES COURSES(COURSEID),
	CONSTRAINT FK_EXAMMARK_CERTIFICATEID FOREIGN KEY(CERTIFICATEID) REFERENCES CERTIFICATES(CERTIFICATEID),
	CONSTRAINT FK_EXAMMARK_SUBJECTID FOREIGN KEY(SUBJECTID) REFERENCES SUBJECTS(SUBJECTID)
)

