/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import aplication.Registers;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ADMIN
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    private final Registers std;
    private final DefaultTableModel tableModelReg = new DefaultTableModel();

    public HomeJFrame() {
        this.std = new Registers();
        initComponents();

    }

    private void showDataReg() throws SQLException {
        String IDCard = txtSearch.getText();
        ResultSet result = std.showIDCard(IDCard);
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[4];
                rows[0] = result.getString("STUDENT_NAME"); // lấy dữ liệu tại cột số 1 (ứng với mã so)
                rows[1] = result.getString("CERTIFICATE_NAME");
                rows[2] = result.getString("EXAM_DATE");
                rows[3] = result.getString("ID_NUM");
                tableModelReg.addRow(rows); // đưa dòng dữ liệu vào tableModel
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrintCertificate1 = new javax.swing.JButton();
        btnManagementSubject = new javax.swing.JButton();
        btnManagementMark = new javax.swing.JButton();
        btnManagementCertificateCer = new javax.swing.JButton();
        btnRegistryStudent = new javax.swing.JButton();
        btnManagementCertificate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbSystemManagementCer = new javax.swing.JLabel();
        lbImg = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSearch = new javax.swing.JTable();
        btnManagementStudent = new javax.swing.JButton();
        btnPrintCertificate = new javax.swing.JButton();
        btnStudentResult = new javax.swing.JButton();
        btnStudentFail = new javax.swing.JButton();
        btnManagêmntUser = new javax.swing.JButton();
        btnManageCourse = new javax.swing.JButton();

        btnPrintCertificate1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnPrintCertificate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exam.png"))); // NOI18N
        btnPrintCertificate1.setText("Print Certificate");
        btnPrintCertificate1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrintCertificate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrintCertificate1MousePressed(evt);
            }
        });
        btnPrintCertificate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCertificate1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnManagementSubject.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManagementSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subject.png"))); // NOI18N
        btnManagementSubject.setText("Management Subject");
        btnManagementSubject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManagementSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManagementSubjectMousePressed(evt);
            }
        });
        btnManagementSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementSubjectActionPerformed(evt);
            }
        });

        btnManagementMark.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManagementMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mark.png"))); // NOI18N
        btnManagementMark.setText("Management Mark");
        btnManagementMark.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManagementMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManagementMarkMousePressed(evt);
            }
        });
        btnManagementMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementMarkActionPerformed(evt);
            }
        });

        btnManagementCertificateCer.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManagementCertificateCer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certificate_cer.png"))); // NOI18N
        btnManagementCertificateCer.setText("Management Certificate Store");
        btnManagementCertificateCer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManagementCertificateCer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManagementCertificateCerMousePressed(evt);
            }
        });
        btnManagementCertificateCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementCertificateCerActionPerformed(evt);
            }
        });

        btnRegistryStudent.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnRegistryStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registr.png"))); // NOI18N
        btnRegistryStudent.setText("Registry Student");
        btnRegistryStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistryStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistryStudentMousePressed(evt);
            }
        });
        btnRegistryStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistryStudentActionPerformed(evt);
            }
        });

        btnManagementCertificate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManagementCertificate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certi.png"))); // NOI18N
        btnManagementCertificate.setText("Management Certificate");
        btnManagementCertificate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManagementCertificate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManagementCertificateMousePressed(evt);
            }
        });
        btnManagementCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementCertificateActionPerformed(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbSystemManagementCer.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lbSystemManagementCer.setText("SYSTEM MANAGEMENT CERTIFICATE");

        lbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manage.png"))); // NOI18N

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CERTIFICATE", "EXAM DATE", "No"
            }
        ));
        jScrollPane1.setViewportView(TableSearch);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(txtSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch)
                                .addGap(144, 144, 144))
                            .addComponent(lbSystemManagementCer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbSystemManagementCer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE))))
        );

        btnManagementStudent.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManagementStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student.png"))); // NOI18N
        btnManagementStudent.setText("Management Student");
        btnManagementStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManagementStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManagementStudentMousePressed(evt);
            }
        });
        btnManagementStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementStudentActionPerformed(evt);
            }
        });

        btnPrintCertificate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnPrintCertificate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exam.png"))); // NOI18N
        btnPrintCertificate.setText("Print Certificate");
        btnPrintCertificate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrintCertificate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrintCertificateMousePressed(evt);
            }
        });
        btnPrintCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCertificateActionPerformed(evt);
            }
        });

        btnStudentResult.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnStudentResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/studentresult.png"))); // NOI18N
        btnStudentResult.setText("Student Result");
        btnStudentResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStudentResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStudentResultMousePressed(evt);
            }
        });
        btnStudentResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentResultActionPerformed(evt);
            }
        });

        btnStudentFail.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnStudentFail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fail.png"))); // NOI18N
        btnStudentFail.setText("Student Fail");
        btnStudentFail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStudentFail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStudentFailMousePressed(evt);
            }
        });
        btnStudentFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentFailActionPerformed(evt);
            }
        });

        btnManagêmntUser.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManagêmntUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exam.png"))); // NOI18N
        btnManagêmntUser.setText("Management User");
        btnManagêmntUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManagêmntUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManagêmntUserMousePressed(evt);
            }
        });
        btnManagêmntUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagêmntUserActionPerformed(evt);
            }
        });

        btnManageCourse.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnManageCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/course.png"))); // NOI18N
        btnManageCourse.setText("Management Course");
        btnManageCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManageCourseMousePressed(evt);
            }
        });
        btnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManagementMark, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagementSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagementStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagementCertificateCer, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagementCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistryStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentFail, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentResult, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrintCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagêmntUser, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManagementCertificate, btnManagementCertificateCer, btnManagementMark, btnManagementStudent, btnManagementSubject, btnPrintCertificate, btnRegistryStudent, btnStudentFail, btnStudentResult});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistryStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManagementCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManagementCertificateCer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManagementSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManagementStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManagementMark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentResult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStudentFail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManagêmntUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManagementCertificate, btnManagementCertificateCer, btnManagementMark, btnManagementStudent, btnManagementSubject, btnManagêmntUser, btnPrintCertificate, btnRegistryStudent, btnStudentFail, btnStudentResult});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagementSubjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagementSubjectMousePressed
        try {
            new SubjectJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(SubjectJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnManagementSubjectMousePressed

    private void btnManagementSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementSubjectActionPerformed

    }//GEN-LAST:event_btnManagementSubjectActionPerformed

    private void btnManagementMarkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagementMarkMousePressed
        try {
            new MarkEntryJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnManagementMarkMousePressed

    private void btnManagementMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagementMarkActionPerformed

    private void btnManagementCertificateCerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagementCertificateCerMousePressed
        try {
            new ManagerCERJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManagerCERJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnManagementCertificateCerMousePressed

    private void btnManagementCertificateCerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementCertificateCerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagementCertificateCerActionPerformed

    private void btnRegistryStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistryStudentMousePressed
        try {
            new RegistryJFrame().setVisible(true);
        } catch (Exception e) {
            e.getMessage();
        }
        this.dispose();
    }//GEN-LAST:event_btnRegistryStudentMousePressed

    private void btnRegistryStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistryStudentActionPerformed

    }//GEN-LAST:event_btnRegistryStudentActionPerformed

    private void btnManagementCertificateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagementCertificateMousePressed
        try {
            new CertificateJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CertificateJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnManagementCertificateMousePressed

    private void btnManagementCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagementCertificateActionPerformed

    private void btnManagementStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagementStudentMousePressed
        try {
            new StudentJFrame().setVisible(true);
        } catch (SQLException e) {
            e.getMessage();
        }
        this.dispose();
    }//GEN-LAST:event_btnManagementStudentMousePressed

    private void btnManagementStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagementStudentActionPerformed

    private void btnPrintCertificateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintCertificateMousePressed
        new PrintCertificateJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrintCertificateMousePressed

    private void btnPrintCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCertificateActionPerformed

    }//GEN-LAST:event_btnPrintCertificateActionPerformed

    private void btnStudentResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentResultMousePressed
        try {
            new StudentResult().setVisible(true);
        } catch (SQLException e) {
            e.getMessage();
        }
        this.dispose();
    }//GEN-LAST:event_btnStudentResultMousePressed

    private void btnStudentResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentResultActionPerformed

    private void btnStudentFailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentFailMousePressed
        try {
            new StudentFailJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(StudentFailJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnStudentFailMousePressed

    private void btnStudentFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentFailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentFailActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        while (tableModelReg.getRowCount() > 0) {
            tableModelReg.removeRow(0);
        }
        String[] colsReg = {"NAME", "CERTIFICATE", "EXAM DATE", "No"};
// đặt tiêu đề cột cho tableModel
        tableModelReg.setColumnIdentifiers(colsReg);

        TableSearch.setModel(tableModelReg);
        // Canh giữa tiêu đề trong bảng
        JTableHeader Thearder = TableSearch.getTableHeader();
        ((DefaultTableCellRenderer) Thearder.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        try {
            showDataReg();
        } catch (SQLException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnPrintCertificate1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintCertificate1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintCertificate1MousePressed

    private void btnPrintCertificate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCertificate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintCertificate1ActionPerformed

    private void btnManagêmntUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagêmntUserMousePressed
        try {
            new MainJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnManagêmntUserMousePressed

    private void btnManagêmntUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagêmntUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagêmntUserActionPerformed

    private void btnManageCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCourseMousePressed
           try {
                new CourseJFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(CourseJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
           this.dispose();
    }//GEN-LAST:event_btnManageCourseMousePressed

    private void btnManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSearch;
    private javax.swing.JButton btnManageCourse;
    private javax.swing.JButton btnManagementCertificate;
    private javax.swing.JButton btnManagementCertificateCer;
    private javax.swing.JButton btnManagementMark;
    private javax.swing.JButton btnManagementStudent;
    private javax.swing.JButton btnManagementSubject;
    private javax.swing.JButton btnManagêmntUser;
    private javax.swing.JButton btnPrintCertificate;
    private javax.swing.JButton btnPrintCertificate1;
    private javax.swing.JButton btnRegistryStudent;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnStudentFail;
    private javax.swing.JButton btnStudentResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbSystemManagementCer;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
