/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import aplication.ExamMarks;
import aplication.ReportExam;
import database.DBconnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author David Nghi
 */
public class MarkEntryJFrame extends javax.swing.JFrame {

    private final ExamMarks examObj = new ExamMarks();
    private boolean flag = true;
    private final DefaultTableModel tableModelExam = new DefaultTableModel();

    private void showDataExam() throws SQLException {
        ResultSet result = examObj.showExam();
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[5];
                rows[0] = result.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã so)
                rows[1] = result.getString(2);
                rows[2] = result.getString(3);
                rows[3] = result.getString(4);
                rows[4] = result.getString(5);
                tableModelExam.addRow(rows); // đưa dòng dữ liệu vào tableModel
            }
        } catch (SQLException e) {
        }
    }
//Ham xoa du lieu trong tableModel

    private void clearDataExam() throws SQLException {
//Lay chi so dong cuoi cung
        int n = tableModelExam.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModelExam.removeRow(i);//Remove tung dong
        }
    }

    private void setNullExam() {
        this.txtStuName.setText(null);
        this.txtSubName.setText(null);
        this.txtMark.setText(null);
    }

    private void setClockID_Sub(boolean a) {
//Khoa hoac mo khoa cho Cac JTextField
        this.txtStuName.setEnabled(!a);
        this.txtSubName.setEnabled(!a);
    }

    private void setClockExam(boolean a) {
//Khoa hoac mo khoa cho Cac JTextField
        this.cbtIDNum.setEnabled(!a);
        this.txtStuName.setEnabled(!a);
        this.cbtIDSubject.setEnabled(!a);
        this.txtSubName.setEnabled(!a);
        this.txtMark.setEnabled(!a);
    }
//Ham khoa cac Button

    private void setButtonExam(boolean a) {
//Vo hieu hoac co hieu luc cho cac JButton
        this.btnExamMarkAdd.setEnabled(a);
        this.btnExamMarkDelete.setEnabled(a);
        this.btnExamMarkEdit.setEnabled(a);
        this.btnExamMarkSave.setEnabled(!a);
        this.btnExamMarkReport.setEnabled(!a);
        this.btnExamMarkReset.setEnabled(!a);
        this.btnExamMarkClose.setEnabled(a);
    }

    private void loadSubject() {
        cbtIDSubject.removeAllItems();
        DBconnect.loadDataCombobox("SELECT * FROM DETAIL_CERTIFICATE ", this.cbtIDSubject, "SUBJECT_ID");
        String query = "SELECT * FROM DETAIL_CERTIFICATE WHERE SUBJECT_ID = ?";
        DBconnect.loadDataTextfield(query, this.cbtIDSubject, this.txtSubName, "SUBJECT_NAME");
    }

    private void loadStudents() {
        cbtIDNum.removeAllItems();
        DBconnect.loadDataCombobox("SELECT * FROM STUDENT_CER ", this.cbtIDNum, "ID_NUM");
        String query = "SELECT * FROM STUDENT_CER WHERE ID_NUM = ?";
        DBconnect.loadDataTextfield(query, this.cbtIDNum, this.txtStuName, "STUDENT_ID");
    }

    public MarkEntryJFrame() throws SQLException {
        initComponents();
        jLabelNotify.setVisible(false);
        String[] colsReg = {"ID Subject", "Subject name", "ID Number", "Full name", "Mark of Exam"};
// đặt tiêu đề cột cho tableModel
        tableModelExam.setColumnIdentifiers(colsReg);
// kết nối jtable với tableModel
        jTableExamMark.setModel(tableModelExam);
//gọi hàm ShowData để đưa dữ liệu vào tableModel
        showDataExam();
        loadSubject();
        loadStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMark = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbtIDNum = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbtIDSubject = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSubName = new javax.swing.JTextField();
        btnExamMarkAdd = new javax.swing.JButton();
        btnExamMarkDelete = new javax.swing.JButton();
        btnExamMarkEdit = new javax.swing.JButton();
        btnExamMarkSave = new javax.swing.JButton();
        btnExamMarkReport = new javax.swing.JButton();
        btnExamMarkClose = new javax.swing.JButton();
        btnExamMarkReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExamMark = new javax.swing.JTable();
        btnChangePass = new javax.swing.JButton();
        jLabelNotify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mark.png"))); // NOI18N
        jLabel1.setText("MARK");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iduser.png"))); // NOI18N
        jLabel2.setText("ID NUMBER");

        cbtIDNum.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbtIDNum.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbtIDNumPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subjectid.png"))); // NOI18N
        jLabel3.setText("Subject ID");

        cbtIDSubject.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbtIDSubject.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbtIDSubjectPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fullname.png"))); // NOI18N
        jLabel4.setText("Student name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subject.png"))); // NOI18N
        jLabel5.setText("Subject name");

        btnExamMarkAdd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnExamMarkAdd.setText("Add");
        btnExamMarkAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMarkAddMouseClicked(evt);
            }
        });

        btnExamMarkDelete.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnExamMarkDelete.setText("Delete");
        btnExamMarkDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMarkDeleteMouseClicked(evt);
            }
        });

        btnExamMarkEdit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnExamMarkEdit.setText("Edit");
        btnExamMarkEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMarkEditMouseClicked(evt);
            }
        });

        btnExamMarkSave.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnExamMarkSave.setText("Save");
        btnExamMarkSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMarkSaveMouseClicked(evt);
            }
        });

        btnExamMarkReport.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        btnExamMarkReport.setText("Report");
        btnExamMarkReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExamMarkReportMousePressed(evt);
            }
        });

        btnExamMarkClose.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnExamMarkClose.setText("Close");
        btnExamMarkClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMarkCloseMouseClicked(evt);
            }
        });

        btnExamMarkReset.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExamMarkReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset1.png"))); // NOI18N
        btnExamMarkReset.setText("Reset");
        btnExamMarkReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMarkResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbtIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(41, 41, 41)
                            .addComponent(cbtIDSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(btnExamMarkAdd))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(btnExamMarkEdit)
                                    .addGap(39, 39, 39)
                                    .addComponent(btnExamMarkDelete))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(txtMark, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExamMarkSave)
                        .addComponent(jLabel5)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubName, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(txtStuName)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnExamMarkReset)
                        .addGap(26, 26, 26)
                        .addComponent(btnExamMarkReport)
                        .addGap(28, 28, 28)
                        .addComponent(btnExamMarkClose)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbtIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtSubName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(cbtIDSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMark, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExamMarkAdd)
                    .addComponent(btnExamMarkDelete)
                    .addComponent(btnExamMarkEdit)
                    .addComponent(btnExamMarkSave)
                    .addComponent(btnExamMarkReport)
                    .addComponent(btnExamMarkClose)
                    .addComponent(btnExamMarkReset))
                .addGap(32, 32, 32))
        );

        jTableExamMark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID NUM", "Student Name", "Subject ID", "Subject Name", "Mark"
            }
        ));
        jTableExamMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExamMarkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExamMark);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnChangePass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/changpassword.png"))); // NOI18N
        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        jLabelNotify.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelNotify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notify.png"))); // NOI18N
        jLabelNotify.setText("Notify: Database has been Successfully");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelNotify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangePass)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNotify)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtIDNumPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbtIDNumPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String query = "SELECT * FROM STUDENT_CER WHERE ID_NUM = ?";
        DBconnect.loadDataTextfield(query, this.cbtIDNum, this.txtStuName, "STUDENT_ID");
    }//GEN-LAST:event_cbtIDNumPopupMenuWillBecomeInvisible

    private void cbtIDSubjectPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbtIDSubjectPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String query = "SELECT * FROM DETAIL_CERTIFICATE WHERE SUBJECT_ID = ?";
        DBconnect.loadDataTextfield(query, this.cbtIDSubject, this.txtSubName, "SUBJECT_NAME");
    }//GEN-LAST:event_cbtIDSubjectPopupMenuWillBecomeInvisible

    private void btnExamMarkCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
         UserFrmForm dialog = null;
            try {
                dialog = new UserFrmForm();
            } catch (SQLException ex) {
                Logger.getLogger(UserFrmForm.class.getName()).log(Level.SEVERE, null, ex);
            }
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        
    }//GEN-LAST:event_btnExamMarkCloseMouseClicked

    private void btnExamMarkReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkReportMousePressed
        // TODO add your handling code here:
        ReportExam.ExportExcel(jTableExamMark);
    }//GEN-LAST:event_btnExamMarkReportMousePressed

    private void btnExamMarkResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkResetMouseClicked
        // TODO add your handling code here:
        setNullExam();
        setClockExam(true);
        setButtonExam(true);
    }//GEN-LAST:event_btnExamMarkResetMouseClicked

    private void btnExamMarkAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkAddMouseClicked
        // TODO add your handling code here:
        setClockID_Sub(false);
        setNullExam();//Xoa trang TextField
        setClockExam(false);//Mo khoa TextField
        setButtonExam(false);//Goi ham khoa cac Button
        this.txtStuName.enable(false);
        this.txtSubName.enable(false);
        flag = true;
    }//GEN-LAST:event_btnExamMarkAddMouseClicked

    private void btnExamMarkDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkDeleteMouseClicked
        // TODO add your handling code here:

                jLabelNotify.setVisible(false);
        String idIdNum = (String) cbtIDNum.getSelectedItem();
        String idSub = (String) cbtIDSubject.getSelectedItem();
        try {
            if (idIdNum.length() == 0 && idSub.length() == 0) {
                JOptionPane.showMessageDialog(null, "Choose a ID item for delete",
                        "Message", 1);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Do you want to delete " + idSub + " and " + idIdNum + "this item ? ", "Message", 2) == 0) {
                    examObj.deleteDataExam(idSub,idIdNum);//goi ham xoa du lieu theo ma loai
                    clearDataExam();//Xoa du lieu trong tableModel
                    showDataExam();//Do du lieu vao table Model
                    setNullExam();//Xoa trang Textfield
                    jLabelNotify.setVisible(true);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Fail", "Message", 1);
        }
    }//GEN-LAST:event_btnExamMarkDeleteMouseClicked

    private void btnExamMarkEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkEditMouseClicked
        // TODO add your handling code here:     
        jLabelNotify.setVisible(false);
        
        String idNum = (String) cbtIDNum.getSelectedItem();
        String idSub = (String) cbtIDSubject.getSelectedItem();
        //JComboBox a = new JComboBox(cbtIDNum.getSelectedObjects());
        this.txtStuName.enable(false);
        this.txtSubName.enable(false);
        if (idNum.length() == 0 || idSub.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose a id item for edit",
                    "Message", 1);
        } else {
            setClockExam(false);//Mo khoa cac TextField
            this.txtStuName.enable(false);
            this.txtSubName.enable(false);
            this.cbtIDNum.setEnabled(false);
            this.cbtIDSubject.setEnabled(false);
            //this.txtMark.enable(false);
            setButtonExam(false); //Khoa cac Button
            flag = false; //Gan cothem=false de ghi nhan trang thai la sua
        }
    }//GEN-LAST:event_btnExamMarkEditMouseClicked

    private void btnExamMarkSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMarkSaveMouseClicked
        // TODO add your handling code here:
                   //cbtIDNum,txtStuName,cbtIDSubject,txtSubName,txtMark
        //btnExamMarkAdd
        
        String idSub = (String) cbtIDSubject.getSelectedItem();
        String subName = txtSubName.getText();
        String idNum = (String) cbtIDNum.getSelectedItem();
        String stuName = txtStuName.getText();
        float mExam = Float.parseFloat(txtMark.getText());
        if (idSub.length() == 0) {
            JOptionPane.showMessageDialog(null, "Subject is empty. Please add subject at a from left!", "Message", 1);
            txtMark.requestFocus();
        } else if (idNum.length() == 0) {
            JOptionPane.showMessageDialog(null, "Identity number of student is empty. Please add student at a from left!", "Message", 1);
            txtMark.requestFocus();        
        } else if (mExam < 0) {
            JOptionPane.showMessageDialog(null, "Mark is less zero . Please add number of over than zero at a from left!", "Message", 1);
            txtMark.requestFocus();        
        }else {
            try {
                if (flag == true) {
                    examObj.insertDataExam(idSub, idNum, mExam);
                    jLabelNotify.setVisible(true);
                } else {
                    examObj.editDataExam(idSub, idNum, mExam);
                    jLabelNotify.setVisible(true);
                }

                clearDataExam(); //goi ham xoa du lieu tron tableModel
                showDataExam(); //Do lai du lieu vao Table Model
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Updated successfull",
                        "Message", 1);
            }
            setClockExam(false);
            setButtonExam(true);
        }
    }//GEN-LAST:event_btnExamMarkSaveMouseClicked

    private void jTableExamMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExamMarkMouseClicked
        // TODO add your handling code here:
        try {
            //Lay chi so dong dang chon
            int row = this.jTableExamMark.getSelectedRow();
            TableModel model = jTableExamMark.getModel();
            String subID = (this.jTableExamMark.getModel().getValueAt(row, 0)).toString();
            String stuName = (this.jTableExamMark.getModel().getValueAt(row, 1)).toString();
            //System.out.println(stuID);

            //ResultSet rs = regObj.showIDStu(stuID);//Goi ham lay du lieu theo
            String idNum = (this.jTableExamMark.getModel().getValueAt(row, 2)).toString();
            String StuName = (this.jTableExamMark.getModel().getValueAt(row, 3)).toString();
            String mark = (this.jTableExamMark.getModel().getValueAt(row, 4)).toString();
            
            //ResultSet rs1 = regObj.showIDCer(cerID);//Goi ham lay du lieu
            ResultSet rs2 = examObj.showIDExam(subID,idNum);//Goi ham lay du lieu theo
            if (rs2.next()) {
                this.cbtIDSubject.setSelectedItem(rs2.getString("SUBJECT_ID"));
                this.txtSubName.setText(rs2.getString("SUBJECT_NAME"));
                this.cbtIDNum.setSelectedItem(rs2.getString("ID_NUM"));
                this.txtStuName.setText(rs2.getString("STUDENT_NAME"));
                this.txtMark.setText(rs2.getString("MARK"));
            }
            String query = "SELECT * FROM STUDENT_CER WHERE ID_NUM = ?";
            DBconnect.loadDataTextfield(query, this.cbtIDNum, this.txtStuName, "STUDENT_ID");
            String querySub = "SELECT * FROM DETAIL_CERTIFICATE WHERE SUBJECT_ID = ?";
            DBconnect.loadDataTextfield(querySub, this.cbtIDSubject, this.txtSubName, "SUBJECT_NAME");

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jTableExamMarkMouseClicked

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        try {
                new ChangePasswordJFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ChangePasswordJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        this.dispose();
    }//GEN-LAST:event_btnChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkEntryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkEntryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkEntryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkEntryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MarkEntryJFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(MarkEntryJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnExamMarkAdd;
    private javax.swing.JButton btnExamMarkClose;
    private javax.swing.JButton btnExamMarkDelete;
    private javax.swing.JButton btnExamMarkEdit;
    private javax.swing.JButton btnExamMarkReport;
    private javax.swing.JButton btnExamMarkReset;
    private javax.swing.JButton btnExamMarkSave;
    private javax.swing.JComboBox<String> cbtIDNum;
    private javax.swing.JComboBox<String> cbtIDSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNotify;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExamMark;
    private javax.swing.JTextField txtMark;
    private javax.swing.JTextField txtStuName;
    private javax.swing.JTextField txtSubName;
    // End of variables declaration//GEN-END:variables
}
