/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import aplication.Login;
import aplication.Users;
import com.sun.glass.events.KeyEvent;
import database.DBconnect;
import database.MD5Password;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Nghi
 */
public class UserFrmForm extends javax.swing.JFrame {

    private final Users us = new Users();
    static Connection conn;
    boolean loginState;
    public static String username;
    public static Login lg = new Login();
    private final DefaultTableModel tableModel = new DefaultTableModel();

    public UserFrmForm() throws SQLException {
        initComponents();

        showData();
//goi Ham xoa trang cac TextField
    }

    /**
     * Creates new form UserFrmForm
     */
    public void showData() throws SQLException {

    }
    private void logUsers(){
        conn = DBconnect.getConnect();
        try {

            username = txtUsername.getText();
            String password = txtPassword.getText();
            String mdPass = MD5Password.mdFivePass(password);
            if(username.trim().isEmpty() && password.trim().isEmpty()){
                txtmessageUsername.setText("Username and password is empty");
            }else if (username.matches("^[a-zA-Z0-9_]{1,20}+( [a-zA-Z0-9_]{1,20}+)*$")== false || username.trim().isEmpty()) {
                txtmessageUsername.setText("It cannot empty, special characters, capital letter");
                if(username.matches("[!@#$%^&*(),.?\":{}|<>][A-Z]\"s") == false)
                    txtUsername.setText(" special characters ");
                txtUsername.requestFocus();
            } else if (mdPass.matches(".{1,}") == false || password.trim().isEmpty()) {
                txtPassword.setText("Password cannot empty");
                txtPassword.requestFocus();
            } else {
                ResultSet rsAdmin = lg.showAdmin(username, password);
                if (rsAdmin.next()) {
                    JFrame frame = new MainJFrame();
                    frame.setVisible(true);
                    this.dispose();
                } else {
                    ResultSet rsKeeper = lg.showKeeper(username, password);
                    if (rsKeeper.next()) {
                        JFrame frame = new MarkEntryJFrame();
                        frame.setVisible(true);
                        this.dispose();
                    }else{
                        txtPassword.setText("Username or Password not correct");
                    }
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed, the port may not match!", "Message", 1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUserCancel = new javax.swing.JButton();
        btnLoginUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbUsername1 = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtmessageUsername = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmUser"); // NOI18N

        btnUserCancel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnUserCancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Nghi\\Desktop\\eProject-Sem2\\eProjectSem2\\Applications\\MCerSoft\\src\\img\\user_cancel.png")); // NOI18N
        btnUserCancel.setText("Cancel");
        btnUserCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserCancelMouseClicked(evt);
            }
        });
        btnUserCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserCancelActionPerformed(evt);
            }
        });

        btnLoginUser.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnLoginUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Nghi\\Desktop\\eProject-Sem2\\eProjectSem2\\Applications\\MCerSoft\\src\\img\\icons8-login-48.png")); // NOI18N
        btnLoginUser.setText("Login");
        btnLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Nghi\\Desktop\\eProject-Sem2\\eProjectSem2\\Applications\\MCerSoft\\src\\img\\user_u.png")); // NOI18N

        lbUsername1.setBackground(java.awt.Color.lightGray);
        lbUsername1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbUsername1.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Nghi\\Desktop\\eProject-Sem2\\eProjectSem2\\Applications\\MCerSoft\\src\\img\\user_admin.png")); // NOI18N
        lbUsername1.setText("Username");

        lbpassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbpassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Nghi\\Desktop\\eProject-Sem2\\eProjectSem2\\Applications\\MCerSoft\\src\\img\\icons8-key-48.png")); // NOI18N
        lbpassword.setText("  Password");

        txtUsername.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("LOGIN TO SYSTEM");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbUsername1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtmessageUsername)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLoginUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUserCancel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmessageUsername)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbpassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginUser)
                    .addComponent(btnUserCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("txtmessageUsername");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginUserActionPerformed
        // TODO add your handling code here:
        logUsers();
    }//GEN-LAST:event_btnLoginUserActionPerformed

    private void btnUserCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserCancelActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            logUsers();
        }
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            logUsers();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnUserCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnUserCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            UserFrmForm dialog = null;
            try {
                dialog = new UserFrmForm();
            } catch (SQLException ex) {
                Logger.getLogger(UserFrmForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginUser;
    private javax.swing.JButton btnUserCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbUsername1;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel txtmessageUsername;
    // End of variables declaration//GEN-END:variables
}
